# Generated by Django 2.2.27 on 2022-03-19 23:04

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_tmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TModel',
        ),
    ]
