# Generated by Django 2.2.27 on 2022-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesmodel',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
